services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - ./.docker-data/redis:/data
    restart: unless-stopped